---
- name: Install clickhouse in ubuntu
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Add repository clickhouse
      become: true
      block:
        - name: Install dependencies
          ansible.builtin.apt:
            name:
              - curl
              - gnupg
              - ca-certificates
              - apt-transport-https
        - name: Get key clickhouse repository
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
            dest: /usr/share/keyrings/clickhouse-keyring.asc
            mode: '0755'
        - name: Add clickhouse in apt lists
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.asc] https://packages.clickhouse.com/deb stable main"
    - name: Install Clickhouse service
      become: true
      ansible.builtin.apt:
        name:
          - clickhouse-common-static={{ clickhouse_version }}
          - clickhouse-client={{ clickhouse_version }}
          - clickhouse-server={{ clickhouse_version }}
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
- name: Install Vector service
  hosts: clickhouse
  handlers:
    - name: Restart vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Get Vector archive
      become: true
      block:
        - name: Make directory for Unarchive Vector
          ansible.builtin.file:
            path: "/vector"
            state: "directory"
            mode: '0755'
        - name: Download Vector archive
          ansible.builtin.get_url:
            url: https://packages.timber.io/vector/{{ vector_version }}/{{ vector_arh_file }}.tar.gz
            dest: /tmp/{{ vector_arh_file }}.tar.gz
            mode: '0755'
        - name: Unarchive Vector
          ansible.builtin.unarchive:
            src: /tmp/{{ vector_arh_file }}.tar.gz
            remote_src: true
            dest: /vector
    - name: Configure service Vector
      become: true
      block:
        - name: Make dir
          ansible.builtin.file:
            path: "/etc/vector"
            state: directory
            mode: '0755'
        - name: Config vector
          ansible.builtin.template:
            src: templates/vector.yaml
            dest: /etc/vector/vector.yaml
            mode: '0655'
          notify: Restart vector
        - name: Add the group vector
          ansible.builtin.group:
            name: vector
            state: present
        - name: Add the user vector
          ansible.builtin.user:
            name: vector
            shell: /sbin/nologin
            group: vector
            create_home: false
            system: true
        - name: Make dir
          ansible.builtin.file:
            path: "/var/lib/vector"
            state: directory
            owner: vector
            group: vector
            mode: '0755'
        - name: Copy vector exec
          ansible.builtin.copy:
            src: /vector/vector-x86_64-unknown-linux-musl/bin/vector
            remote_src: true
            dest: /usr/bin/vector
            group: root
            owner: root
            mode: '0755'
        - name: Add vector.service in systemd
          ansible.builtin.copy:
            src: /vector/vector-x86_64-unknown-linux-musl/etc/systemd/vector.service
            remote_src: true
            dest: /etc/systemd/system/vector.service
            owner: root
            group: root
            mode: '0655'
          notify: Restart vector
