---
- name: Install clickhouse in ubuntu
  hosts: clickhouse
  become: true
  roles:
    - clickhouse
  post_tasks:
    - name: Create database
      become: true
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector service
  hosts: vector
  become: true
  roles:
    - vector-role
- name: Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role
