---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx
- name: Copy config nginx
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '644'
  notify: Restart Nginx server
- name: Copy default site
  become: true
  ansible.builtin.template:
    src: files/default
    dest: /etc/nginx/sites-enabled
    mode: '644'
  notify: Restart Nginx server
- name: Get lighthouse
  become: true
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /var/www/html/lighthouse
    version: master
    single_branch: true
